language: python

cache: pip

before_script:
  - .travis/sync-github.sh
  - pip install moban

script:
  - .travis/check-whitespace.sh
  - moban
  - git diff --exit-code

after_success:
  - .travis/build-parent.sh
