language: python

cache: pip

before_script:
  - git clone --depth 1 https://github.com/github/gitignore ../temp-github-gitignore
  - find ../temp-github-gitignore -name '*.gitignore' | xargs sed -i 's/ *$//g;$a\'
  - pip install moban

script:
  - .travis/check-whitespace.sh
  - moban

after_success:
  - .travis/build-parent.sh
